do $$
declare
  guestbook_id_type text;
begin
  if to_regclass('public.guestbook') is null then
    return;
  end if;

  select data_type
  into guestbook_id_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'guestbook'
    and column_name = 'id'
  limit 1;

  if to_regclass('public.comments') is null then
    if guestbook_id_type = 'uuid' then
      create extension if not exists pgcrypto;

      execute '
        create table public.comments (
          id uuid primary key default gen_random_uuid(),
          post_id uuid not null references public.guestbook(id) on delete cascade,
          author text not null check (char_length(trim(author)) between 1 and 30),
          content text not null check (char_length(trim(content)) between 1 and 500),
          created_at timestamptz not null default timezone(''utc'', now())
        )
      ';
    else
      execute '
        create table public.comments (
          id bigint generated by default as identity primary key,
          post_id bigint not null references public.guestbook(id) on delete cascade,
          author text not null check (char_length(trim(author)) between 1 and 30),
          content text not null check (char_length(trim(content)) between 1 and 500),
          created_at timestamptz not null default timezone(''utc'', now())
        )
      ';
    end if;
  end if;

  create index if not exists idx_comments_post_created_at on public.comments(post_id, created_at asc);

  alter table public.comments enable row level security;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'comments' and policyname = 'Public can read comments'
  ) then
    create policy "Public can read comments"
      on public.comments
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'comments' and policyname = 'Public can insert comments'
  ) then
    create policy "Public can insert comments"
      on public.comments
      for insert
      to anon, authenticated
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'comments' and policyname = 'Public can update comments'
  ) then
    create policy "Public can update comments"
      on public.comments
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'comments' and policyname = 'Public can delete comments'
  ) then
    create policy "Public can delete comments"
      on public.comments
      for delete
      to anon, authenticated
      using (true);
  end if;

  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'comments'
    ) then
      alter publication supabase_realtime add table public.comments;
    end if;
  end if;
end;
$$;
